### ISSUE TITLE
Compatibility with Apache

### ISSUE THREAD

**Issue by elliottmangham** [artifex404/local-bedrock#1]
Hello,

Can you please make this compatible with **Apache** as opposed to only supporting **nginx**?
I understand nginx is recommended by Flywheel but on many occasions, I must use Apache.

Thanks in advance.

**Comment by elliottmangham** [comment]
Bump @artifex404. Will you be supporting Apache2, or advise how to? Thanks!

**Comment by artifex404** [comment]
In the latest commit I added support for Apache server.
