### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by gaysonmccord** [artifex404/local-bedrock#3]
Hi,

When I completed all the steps to install Bedrock on Flywheel and then go to the live site it shows a "403 Forbidden" page. I had to change all instances of the URL within the database from .dev to .local because by default the Site Domain is local-bedrock.local. Would you happen to know what I may be doing wrong?

Also, on a previous issue on this repo "Stuck on 'changing site domain'", I also got stuck on that same step but I closed down flywheel and opened it back up and the installation shows up on the dashboard.

Thanks for your help.

![screen shot 2018-10-13 at 12 20 13 pm](https://user-images.githubusercontent.com/4970219/46907627-6019c600-cee3-11e8-97ea-7ee03a3d208b.png)

**Comment by artifex404** [comment]
When you reopened Local, did the site work as expected?

**Comment by artifex404** [comment]
This has been now fixed with the latest commit and updated instructions.
