### ISSUE TITLE
Permission denied on Step 10.

### ISSUE THREAD

**Issue by chrisjimallen** [artifex404/local-bedrock#6]
On step 10, when trying to run 

`sed -i "s/root \/app\/public\/\;/root \/app\/public\/web\/;/g" /etc/nginx/wordpress/site.conf` 

from within the Virtual machine, I get the following error:

`sed: couldn't close /etc/nginx/wordpress/sed5SGsJM: Permission denied`

<img width="762" alt="screenshot 2018-11-24 at 22 00 57" src="https://user-images.githubusercontent.com/1681063/48973317-a6128f80-f034-11e8-8cd8-2e4c0edd84ac.png">

**Comment by artifex404** [comment]
Are you sure you're not running out of storage space on your computer?

Alse make sure your VirtualBox is updated to the latest version.

**Comment by dajocarter** [comment]
I also ran into this on a brand new computer with this being the first site on a fresh install of Local and VirtualBox.

**Comment by artifex404** [comment]
@dajocarter Could you please show me what the command `whoami && ls -la /etc/nginx/wordpress/site.conf` outputs in the site SSH?

**Comment by dajocarter** [comment]
@artifex404 
```
root
-rw-r--r-- 1 root root 2717 Jun 13 20:08 /etc/nginx/wordpress/site.conf
```

**Comment by artifex404** [comment]
@dajocarter try to run: `sed "s/root \/app\/public\/\;/root \/app\/public\/web\/;/g" /etc/nginx/wordpress/site.conf > /etc/nginx/wordpress/site.conf`

**Comment by dajocarter** [comment]
@artifex404 Yep, that worked. Although you have a typo at the last wordpress (`/etc/nginx/wordpress/site.conf`)

**Comment by artifex404** [comment]
Updated the main instructions to use `sed` without the in place option.

**Comment by chrisjimallen** [comment]
Appreciate you sorting this. Sorry I was late to the party.
