### ISSUE TITLE
Local 3.0.0 Update breaks bedrock structure

### ISSUE THREAD

**Issue by KnowIsPow** [artifex404/local-bedrock#7]
Bedrock is automatically overwritten with standard Wordpress directory structure when .zip is dropped into Flywheel Local with PHP 7.2, NGINX, and MYSQL 5.6.

**Comment by artifex404** [comment]
Newest Local is currently version 2.4.5. I'm trying to support the latest stable Local version. Is the 3.0.0 still a beta version?

**Comment by KnowIsPow** [comment]
That's odd, on their forums they mention up to release 2.4.6, but when downloaded on both Mac OS and Windows, it lists version 3.0.0 under the "About Local" tab and in the name of the download.

**Comment by artifex404** [comment]
You're right. Maybe they unintentionally released the new version? Also the 2.4.5 (mac) does not detect any new versions. I'll check out what's the 3.0.0 version is about.

**Comment by KnowIsPow** [comment]
Looks like they finally announced it https://local.getflywheel.com/community/t/local-by-flywheel-3-0-1/9976

**Comment by artifex404** [comment]
@KnowIsPow Could you please the setup with the newest instructions?

**Comment by artifex404** [comment]
Closing due to innactivity. Issue resolved.
